import = [
    # "~/.config/alacritty/themes/themes/coolnight.toml"
    "~/.config/alacritty/coolnight-theme/coolnight.toml"
]

[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10

# decorations = "Buttonless"

opacity = 0.8
blur = true

option_as_alt = "Both"

[font]
normal.family = "MesloLGS Nerd Font Mono"

#regular
size = 17

#for video
# size = 35.0

# coolnight theme to the themes folder
# curl https://raw.githubusercontent.com/josean-dev/dev-environment-files/main/.config/alacritty/themes/themes/coolnight.toml --output ~/.config/alacritty/themes/themes/coolnight.toml
